# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_consecutive <- function(mat, n) {
    .Call(`_JeuTAKUZU_check_consecutive`, mat, n)
}

